### PR TITLE
Use different strategies for background and save linting.

### PR DESCRIPTION
**Pull request by alecthomas**

### CODE REVIEW

**Comment by alecthomas** [comment]
@ottob this should now work with the custom SublimeLinter environment.

**Comment by alecthomas** [comment]
Let me know if there are any issues.

**Comment by ottob** [comment]
Still path issue:

``` python
env = os.environ.copy()
if self.env:
    env.update(self.env)
print('gometalinter: path: {}'.format(env['PATH']))
```

`gometalinter: path: /usr/bin:/bin:/usr/sbin:/sbin`

```
SublimeLinter: computed PATH using /bin/bash:
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/go/bin
/Applications/Postgres.app/Contents/Versions/latest/bin
/Users/ottob/go/bin
```

This is when I don't start from Terminal

**Comment by ottob** [comment]
And sorry about the tmpdir comment. I didn't realise that it was a Python function from std lib.

**Comment by ottob** [comment]
self.env is not set so `env.update` is not run.

**Comment by ottob** [comment]
And I still get `gometalinter: path: /usr/bin:/bin:/usr/sbin:/sbin`

even if I edit my SublimeLinter config:

```
"paths": {
            "linux": [],
            "osx": [
                "~/go/bin"
            ],
            "windows": []
        },
```

**Comment by alecthomas** [comment]
Yeah I've found the problem. I need to use [lint.util.popen](https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/util.py#L1250) from SublimeLinter, which does all the env setup magic. Should be done soon.

**Comment by ottob** [comment]
Nice!

**Comment by alecthomas** [comment]
Okay, try that one out.

**Comment by ottob** [comment]
Works as expected now. Thanks!

**Comment by alecthomas** [comment]
Brilliant!

**Comment by ottob** [comment]
Perhaps also update the README with known issue: linting code using vendoring will not work in background mode.

**Pull request merged**
