### PR TITLE
Fix: simplify the calls to communicate

### LINKED ISSUE #24: SublimeLinter deprecation warning
I see this warning consistently every time the linter runs. 

```
gometalinter: live linting file.go in /Users/joe/go/src/path/to/file: /Users/joe/go/bin/gometalinter --fast . -I file.go
SublimeLinter: WARNING: `util.communicate` has been deprecated.
```

### PR DESCRIPTION
**Pull request by asfaltboy**
The newest SublimeLinter API does not require setting any of these and will (or should?) do the right thing for us.

Should fix #24

### CODE REVIEW

**Comment by alecthomas** [comment]
Nice! Does it work?

**Comment by asfaltboy** [comment]
Yes seems to work fine for me (I'm using the fork).

By the way is it necessary to create temp dirs/files every time we lint? Perhaps we could reuse the files, or otherwise leave it to `gometalint` to decide somehow? Maybe I can tackle that in another PR if you don't object

**Comment by alecthomas** [comment]
The temp dir is created because some linters will only operate correctly on a whole package. Most of the files are hard links, so there should be very little overhead.

**Comment by asfaltboy** [comment]
The temp dir is normally harmless w/ regards to IO overhead; however, sublime normally gets busy fading the new directories in and out in the sidebar (causing flickering UI). I normally have to add the `.gometalinter-*` to project folders ignore.

If you like I could create a new issue/PR with details and a suggested solution (e.g use default tmpdir location).

**Comment by alecthomas** [comment]
It can't be moved to the default temporary directory, as internal imports then don't work correctly. That is what it did initially.

**Comment by asfaltboy** [comment]
While looking for clues on how gometalinter operates, I just seen that [gometalinter is deprecated][3] in favour of [golangci/golangci-lint][1] and there's [a sublime extension][2], I'm gonna give it a try and see how it operates...

[1]: https://github.com/golangci/golangci-lint
[2]: https://github.com/alecthomas/SublimeLinter-contrib-golang-cilint
[3]: https://github.com/alecthomas/gometalinter/issues/590

**Pull request merged**
